version: "3"
services:

  wordpress:
      image: wordpress
      links:
      - mariadb:mysql
      environment:
      - WORDPRESS_DB_PASSWORD=welcome123
      - WORDPRESS_DB_USER=root
      ports:
      - "80:80"
      volumes:
      - ./html:/var/www/html
  mariadb:
      image: mariadb
      environment:
      - MYSQL_ROOT_PASSWORD=welcome123
      - MYSQL_DATABASE=wordpress
      volumes:
      - ./database:/var/lib/mysql